export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_ERROR = 'USERS_FETCH_ERROR';

export const USERS_ADD = 'USERS_ADD';
export const USERS_EDIT = 'USERS_EDIT';
export const USERS_REMOVE = 'USERS_REMOVE';